# data
path: /train_data
train: /images/train
val: /images/val


# keypoints
# TODO: add keypoints of arms + hands (at least 18 x 2) and face (1)

# classes
names:
  0: left_hand
  1: right_hand
  2: face